export const START_LOADING_SUNDAES = "START_LOADING_SUNDAES";
export const SUCCESSFULLY_LOADED_SUNDAES = "SUCCESSFULLY_LOADED_SUNDAES";
export const START_LOADING_SUNDAE = "START_LOADING_SUNDAE";
export const SUCCESSFULLY_LOADED_SUNDAE = "SUCCESSFULLY_LOADED_SUNDAE";
export const SUCCESSFULLY_CREATED_SUNDAE = "SUCCESSFULLY_CREATED_SUNDAE";
export const SUCCESSFULLY_ADD_VOTE = "SUCCESSFULLY_ADD_VOTE";

